### ISSUE TITLE
headline example looks weird in pdf

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#100]
@juliasilge what do you think about conditionally change these to a bulleted list in the pdf version?

# PDF
<img width="683" alt="Screen Shot 2021-01-10 at 8 10 58 PM" src="https://user-images.githubusercontent.com/14034784/104146570-08978880-5380-11eb-8ebe-897bc9f43a4c.png">

# Website
<img width="788" alt="Screen Shot 2021-01-10 at 8 11 16 PM" src="https://user-images.githubusercontent.com/14034784/104146573-09301f00-5380-11eb-9f70-d57afc6bcdd3.png">

**Comment by juliasilge** [comment]
The other thing I was thinking about trying was conditionally changing it to a quote, but all of them together in one quote block, rather than separate quote blocks, for the PDF. I'm open to whichever looks better in the end.

**Comment by EmilHvitfeldt** [comment]
Tried both approaches, went with bulleted list
<img width="685" alt="Screen Shot 2021-01-16 at 5 17 40 PM" src="https://user-images.githubusercontent.com/14034784/104828976-bc3ac580-5823-11eb-9f43-41376c2152eb.png">
