### ISSUE TITLE
Make sure all the bibtex looks good

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#103]

**Comment by juliasilge** [comment]
There are still a few refs that are not great, like:

> Group, The Open. 2018. “The Open Group Base Specifications Issue 7, 2018 Edition.” https://pubs.opengroup.org/onlinepubs/9699919799/

And:

> https://www.unicode.org/. 2019. “Unicode Text Segmentation.” https://www.unicode.org/reports/tr29/tr29-35.html#Default_Word_Boundaries. 

I'm not sure what we want to do about some of those. Maybe change them to links where possible? Those would show up as footnotes in the paper book.

**Comment by EmilHvitfeldt** [comment]
Ya, I think changing to links is the best option

**Comment by EmilHvitfeldt** [comment]
I'm going to remove the "The Open Group Base Specifications", it is double reference occurring together with "Regular Expressions Cookbook"

**Comment by juliasilge** [comment]
Book is in print! ✅
