### ISSUE TITLE
Reference: but English is not a dominant language around the world.

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#113]
https://github.com/EmilHvitfeldt/smltar/blob/a0ecd97a1f7e0e631cc98cef972f80362e3ea494/01_model_language.Rmd#L96

I would like a link/reference for this claim

> but English is not a dominant language around the world.

**Comment by juliasilge** [comment]
There is a reference for this same claim made in the text above:
https://github.com/EmilHvitfeldt/smltar/blob/84ceb5126e761498ef319f329b49211f5b09847c/01_model_language.Rmd#L72
I don't know if we need to repeat it again? But we could, I suppose.

**Comment by EmilHvitfeldt** [comment]
I'm happy enough with this! It close enough in the text
