### ISSUE TITLE
Note why one might want to avoid using the purrr package

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#119]
https://github.com/EmilHvitfeldt/smltar/blob/f885f862b12495640683414ae7c011de83a06525/02_tokenization.Rmd#L486

**Comment by juliasilge** [comment]
Do you think something is unclear about this? Did you add this because of specific reviewer feedback?

**Comment by EmilHvitfeldt** [comment]
Yes this is based on reviewer feedback

> Should I be worried about purrr dependencies? This is cryptic.

**Comment by EmilHvitfeldt** [comment]
In essence, this is pretty mild since purrr is quite a small dependency if you only need it for `map()`

**Comment by juliasilge** [comment]
Ah yes, I already [made an edit addressing this feedback here](https://github.com/EmilHvitfeldt/smltar/commit/d8a98878b22f575232e7372e6b2a0c2b6a75e876).

**Comment by EmilHvitfeldt** [comment]
I like the wording better in that edit, but it still doesn't explain why one might want to avoid purrr.

Should we change it completely to say something like "we are using the tidyverse in these examples but the ideas presented are agnostic to the packages you are using."?

**Comment by EmilHvitfeldt** [comment]
remove note completely
