### ISSUE TITLE
ethical issues

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#12]
- [Word embeddings quantify 100 years of gender and ethnic stereotypes](https://www.pnas.org/content/115/16/E3635)
- [Introduction to Algorithmic Bias](https://www.youtube.com/watch?v=pThqge9QDn8&list=PLtmWHNX-gukKocXQOkQjuVxglSDYWsSh9&index=4&t=0s)
- [What you need to know about Disinformation](https://www.youtube.com/watch?v=vbva2RN-rbQ&list=PLtmWHNX-gukKocXQOkQjuVxglSDYWsSh9&index=19)

**Comment by juliasilge** [comment]
In one of the modeling chapters, let's reference and discuss the ethics "checklist" of Rachel Thomas. One [possible link to use is here](https://opendatascience.com/odsc-west-2019-keynote-rachel-thomas-on-algorithmic-bias/).

- Should we even be doing this?
- What bias is already in the data?
- Can the code and data be audited?
- What are the error rates for sub-groups?
- What is the accuracy of a simple rule-based alternative?
- What processes are in place to handle appeals or mistakes?
- How diverse is the team that built it?

**Comment by EmilHvitfeldt** [comment]
This has been added in both the modeling prefaces
