### ISSUE TITLE
Clean up presentation of list with blod

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#123]
There is a lot going on here visually. Maybe we should split it so we don't have the bold and non-bold text on the same line

https://github.com/EmilHvitfeldt/smltar/blob/a0ecd97a1f7e0e631cc98cef972f80362e3ea494/04_stemming.Rmd#L235
<img width="685" alt="Screen Shot 2021-02-20 at 10 30 29 PM" src="https://user-images.githubusercontent.com/14034784/108617449-4ea62a00-73cb-11eb-9569-51793c3fe802.png">
<img width="816" alt="Screen Shot 2021-02-20 at 10 30 51 PM" src="https://user-images.githubusercontent.com/14034784/108617450-4f3ec080-73cb-11eb-9e02-b4fa1188239e.png">

**Comment by EmilHvitfeldt** [comment]
New look

<img width="700" alt="Screen Shot 2021-02-21 at 10 42 57 AM" src="https://user-images.githubusercontent.com/14034784/108635009-a4152200-7431-11eb-8e10-d0929c5ed613.png">

**Comment by juliasilge** [comment]
Oh man, I think this is much worse and the original was a lot clearer 😬

**Comment by EmilHvitfeldt** [comment]
oh no! 

I liked the old version of the website a lot but it felt very cramped in the pdf 😬

**Comment by juliasilge** [comment]
All bulleted lists are cramped in PDF so it's probably better to fix bulleted lists overall. I do think the new version shown here is confusing WRT indentation, etc.

**Comment by EmilHvitfeldt** [comment]
I think that is a good idea. I added a separate issue for that
