### ISSUE TITLE
Milder error

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#128]
This warning seems a little hard. I feel like it should be a rmdnote

https://github.com/EmilHvitfeldt/smltar/blob/f1e430c4411391f64a2b569e6729423f7ae274a9/07_ml_classification.Rmd#L158

**Comment by juliasilge** [comment]
I had this as a warning instead of a note because there were so many notes in a row, and the warning is just a "flag" not like a stop sign or anything super scary. I would vote for rolling this change back to avoid so many NOTE NOTE NOTE.

**Comment by EmilHvitfeldt** [comment]
hmm, that is true. It felt a little aggressive but I see the point
