### ISSUE TITLE
Should we add color to the bigger confusion matrices?

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#129]
what do you think @juliasilge? Right now they are a lot of gray

<img width="619" alt="Screen Shot 2021-02-20 at 11 58 35 PM" src="https://user-images.githubusercontent.com/14034784/108619103-9763e000-73d7-11eb-8f9a-19a9c0bd9652.png">

**Comment by juliasilge** [comment]
I think that is probably a good idea visually but then would involve not using `autoplot()`. The `autoplot()` method is not very customizable in this sense, and Max/Davis have not wanted to change that about it. For a blog post, I [overwrote the method in my setup chunk](https://github.com/juliasilge/juliasilge.com/blob/af07e3162bfb90405cac9af4c5bef2bb40648e11/content/blog/datasaurus-multiclass/index.Rmarkdown). 🤷  

We could do something like that in `_common.R` and then not explicitly show using `autoplot()` to make the plots? To avoid being deceptive in that way? I'm not sure what is best. The code to make something like that from scratch is pretty extensive.

**Comment by EmilHvitfeldt** [comment]
If it went the `_common.R` route we could include a reference to it in the Colophon where we also note that all ggplot2 charts are modified to use `theme_minimal()`.
