### ISSUE TITLE
bookdown references style needs more vertical spacing!!

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#148]
<img width="908" alt="Screen Shot 2021-03-21 at 12 34 00 PM" src="https://user-images.githubusercontent.com/14034784/111918307-ba6ac980-8a41-11eb-84fc-e0a1d90f1f2c.png">

**Comment by EmilHvitfeldt** [comment]
find a way to remove "---"

**Comment by juliasilge** [comment]
I'm going to close here and make a new issue for the remaining problem.
