### ISSUE TITLE
Missing footnotes/links from noteboxes in PDF

### ISSUE THREAD

**Issue by juliasilge** [EmilHvitfeldt/smltar#155]
I don't know why these are not rendering correctly but links in noteboxes do not generate footnotes in the PDF. 😕

### Chapter 4:

![Screen Shot 2021-04-04 at 4 17 56 PM](https://user-images.githubusercontent.com/12505835/113522924-a8207d80-9561-11eb-892c-531ce7fbce01.png)

### Chapter 6: 

![Screen Shot 2021-04-04 at 4 30 08 PM](https://user-images.githubusercontent.com/12505835/113523108-1b76bf00-9563-11eb-87d2-8c44194ba404.png)

![Screen Shot 2021-04-04 at 4 31 59 PM](https://user-images.githubusercontent.com/12505835/113523157-55e05c00-9563-11eb-8aac-c0d40133c935.png)

![Screen Shot 2021-04-04 at 4 32 43 PM](https://user-images.githubusercontent.com/12505835/113523167-6690d200-9563-11eb-999e-90ce681ae715.png)

There are bunch more further in the book.

**Comment by EmilHvitfeldt** [comment]
I'll try to generate a reprex we can send out to the world

**Comment by EmilHvitfeldt** [comment]
<img width="679" alt="Screen Shot 2021-04-11 at 5 57 55 PM" src="https://user-images.githubusercontent.com/14034784/114328092-6d35c100-9af0-11eb-8b8a-0e2de851961f.png">
