### ISSUE TITLE
Foreword numbering

### ISSUE THREAD

**Issue by juliasilge** [EmilHvitfeldt/smltar#157]
I think this has come to light because of the PDF but impacts both HTML and PDF; the forewords are being treated as part of the previous chapters in terms of numbering. For example, check out the table in the DL foreword:

![Screen Shot 2021-04-04 at 5 35 47 PM](https://user-images.githubusercontent.com/12505835/113524544-95f80c80-956c-11eb-8b73-dbb9d8681a16.png)
![Screen Shot 2021-04-04 at 5 36 29 PM](https://user-images.githubusercontent.com/12505835/113524546-985a6680-956c-11eb-823e-c95fd19cbe85.png)

But also no numbering in the caption for the PDF? So when it is referenced later, there is nothing to match it to.

**Comment by EmilHvitfeldt** [comment]
closed in https://github.com/EmilHvitfeldt/smltar/commit/13baf472a8238d63d33ff1cfa93d4c77fc8a51fc
