### ISSUE TITLE
Problem with references from authors with multiple references in book: last name as `____`

### ISSUE THREAD

**Issue by juliasilge** [EmilHvitfeldt/smltar#158]
![Screen Shot 2021-04-24 at 10 14 17 PM](https://user-images.githubusercontent.com/12505835/115980502-7e4bec80-a54a-11eb-8850-a1604950b412.png)

In the [final references section](https://smltar.com/references.html), references with the same author are represented with a `___`. In the reference sections after each chapter, we still have these `____` representations even when the first listing of that author is not used in that chapter.

**Comment by EmilHvitfeldt** [comment]
This [stackoverflow post](https://stackoverflow.com/questions/46939456/bibtex-authors-appearing-as-dashed-lines-in-references-when-using-bookdown-and-p) gives us the answers we need
