### ISSUE TITLE
Random crashing in chapter 10

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#163]
When rendering the book with `bookdown::render_book()`, it crashes R hard when it gets to section 10.4 on bpe.

**Comment by juliasilge** [comment]
I supposed we can keep this open for now, but the crashing resolved itself 🤷‍♀️

**Comment by juliasilge** [comment]
I experienced some crashing in Ch 10 when rendering this time around if I had any leftover cache from an unfinished run. I had to delete the cache.

**Comment by juliasilge** [comment]
We think the solution is to delete the chapter-level cache.
