### ISSUE TITLE
Figure 2.1 does not display on current bookdown deployment

### ISSUE THREAD

**Issue by KaiAragaki** [EmilHvitfeldt/smltar#170]
Hello,

I am unable to see figure 2.1 on the bookdown deployment (https://smltar.com/tokenization.html). Instead, this is what I see:

![image](https://user-images.githubusercontent.com/7370516/144758778-9aac0c90-f0fa-4509-8847-0f4f5d21becb.png)

(I see this at all widths - this has been horizontally compressed for your viewing pleasure)

Obviously please close if duplicate or unnecessary.

Thank you for your time!

**Comment by juliasilge** [comment]
There are a number of figures missing, including Fig 10.2.

**Comment by juliasilge** [comment]
@EmilHvitfeldt these figures are still missing, even after your recent re-render. Want to take a look while you have it open?

**Comment by EmilHvitfeldt** [comment]
I figured it out. All the times we used `knitr::include_graphics()` we were using `.pdf` files. They don't appear to work with the html version. I switched to the `.png`s in https://github.com/EmilHvitfeldt/smltar/commit/dac5fb5e37087a70916dbeb47d52cc2092520788 and it is fixed now
