### ISSUE TITLE
Update links to https://www.hvitfeldt.me/

### ISSUE THREAD

**Issue by machinatoonist** [EmilHvitfeldt/smltar#173]
Inset text in Section 6.6 has link to https://www.hvitfeldt.me/blog/tidytuesday-pos-textrecipes-the-office/ that lead me to Google Chrome warning about an out of date SSL certificate.  Suggest updating all links to www.hvitfeldt.me with new path i.e. https://www.emilhvitfeldt.com/post/tidytuesday-pos-textrecipes-the-office/

Thanks for your efforts Emil and Julia!  I'm enjoying the book.

**Comment by EmilHvitfeldt** [comment]
Thank you for finding this error! Should be fixed now
