### ISSUE TITLE
add typographical conventions section

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#34]
- italics
- constant width
- bold

etc

**Comment by juliasilge** [comment]
Conventions for boxes?

**Comment by EmilHvitfeldt** [comment]
It appears that we are using **bold** for package names quite a lot

**Comment by juliasilge** [comment]
In Preface ➡️ Outline, include examples of three infoboxes to show how they are used. Don't go to the trouble of explaining other typographical choices because seems pretty clear/normal.
