### ISSUE TITLE
Explain tf-idf

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#45]

**Comment by juliasilge** [comment]
Probably in tokenization chapter? Or maybe in depth at first use in modeling example.

**Comment by EmilHvitfeldt** [comment]
I think it should be in the tokenization chapter. that way we can easily refer to it in later chapters

**Comment by EmilHvitfeldt** [comment]
and since I now have full control over how tf-idf is calculated in textrecipes we are not limited in what weighing schemes we can talk about

https://nlp.stanford.edu/IR-book/html/htmledition/document-and-query-weighting-schemes-1.html

**Comment by juliasilge** [comment]
Add in word embeddings chapter, where tf-idf is already mentioned (more than a box)

**Comment by EmilHvitfeldt** [comment]
talk about data leakage
