### ISSUE TITLE
check bookdown options

### ISSUE THREAD

**Issue by juliasilge** [EmilHvitfeldt/smltar#58]
A few bookdown options to turn off:

- [x] download PDF/EPUB (need to remove for CRC agreement)
- [x] font options (will be weird with beautiful CSS)
- [ ] ~the edit button???~

**Comment by EmilHvitfeldt** [comment]
I feel like the edit button might be nice to have. It gives people a fast way to PR a typo :)

**Comment by juliasilge** [comment]
Closed in 640a5865928d51c2d53f44e84fcb5547c69d084b
