### ISSUE TITLE
Typos: 6.8, 6.9.3

### ISSUE THREAD

**Issue by DesmondChoy** [EmilHvitfeldt/smltar#79]
Thanks for this book! Just highlighting some typos I came across:

6.8 What evaluation metrics are **appropiate**?

6.9.3: Let’s include seven possible values for each parameter, for a combination of **49** models.
However, the tibble below shows only 36 combinations, presumably because levels was set as 6 and not 7?

On a related note, I note parallel processing is not used in Chapter 6 despite some parts of the workflow being quite time consuming. e.g. tuning. From previous [blog posts](https://juliasilge.com/blog/animal-crossing/), Julia Silge used it with textrecipes; so I'm just wondering is there a reason why its not implemented here?

**Comment by juliasilge** [comment]
Thank you so much for the report @DesmondChoy! 🙌 

If you check out this `.Rmd` that builds this chapter, you can notice that parallel processing is set up in the setup chunk. I can see why that might be confusing. I'm going to open a new issue for us to decide where/how to chat about parallel processing.
