### ISSUE TITLE
Discuss/introduce R packages

### ISSUE THREAD

**Issue by juliasilge** [EmilHvitfeldt/smltar#81]
Feedback says:

> ...adding a 2-3 line summary of the usefulness of each package (at least when it is being introduced for the first time) would go a long way in making this book further self-contained

> It is not clear what the discrim package is being used for in the classification chapter

Right now, the chapters I am writing mostly load each package in the chunk it is first used and the chapters Emil is writing load all packages in one chunk all together. The second approach definitely obfuscates what packages are used for and what users might need in their own work. Let's think through:

- when and how to _load_ packages
- when and how to _discuss_ packages

**Comment by juliasilge** [comment]
Related to #30

**Comment by EmilHvitfeldt** [comment]
I'm in favor of loading the packages as they come. Could we start the chapter with "we load tidymodels as a group of packages" and then load each package individually the first time we use them? We will be double loading them. But I think it is important both show that 

1. tidymodels is a collection that works together
2. what each individual package contribues

**Comment by juliasilge** [comment]
I don't know about loading the tidymodels package individually; I'll think about that. The feedback we got was confusion about packages like textrecipes, discrim, etc -- "what do those do? when do I need to load them vs. not?"

**Comment by EmilHvitfeldt** [comment]
Part of this will depend on the degree we are teaching {tidymodels} and using {tidymodels}

**Comment by juliasilge** [comment]
Think about making a third kind of box + icon to discuss packages/functions

**Comment by EmilHvitfeldt** [comment]
Added specification here: https://github.com/EmilHvitfeldt/smltar/commit/92b708473bec6373407e4e56f6b61a8d6f4e8264

**Comment by EmilHvitfeldt** [comment]
textrecipes, tidymodels, keras, tidytext, discrim? (all add-on parsnip), tidyverse, tokenizers, stopwords

"this is why we are using this package right now"

**Comment by EmilHvitfeldt** [comment]
keras is already fairly well explained in this section

https://github.com/EmilHvitfeldt/smltar/blob/master/08_dl_dnn.Rmd#L8-L10
