### ISSUE TITLE
Update dedications

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#88]
https://github.com/EmilHvitfeldt/smltar/blob/ae4c4deeaabad6ee93371c85d3a88e6607d2b2ed/latex/before_body.tex#L9-L11

**Comment by juliasilge** [comment]
Addressed in c2610c513497f8d6670f9be1d21950a171f5ad67

**Comment by juliasilge** [comment]
Closed in af46e0ec81d7d8d6683b224ea5ea46971f747212
