### ISSUE TITLE
fix alignment of infobox in pdf format

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#91]
<img width="697" alt="Screen Shot 2020-12-25 at 11 32 43 PM" src="https://user-images.githubusercontent.com/14034784/103147407-911ff300-4709-11eb-94ac-37769bb93f9c.png">

**Comment by juliasilge** [comment]
It would be great to use our "special" icons as well, instead of those defaults.

![Screen Shot 2020-12-26 at 7 59 38 PM](https://user-images.githubusercontent.com/12505835/103162975-e95fff00-47b4-11eb-9911-5f34887094c8.png)

**Comment by EmilHvitfeldt** [comment]
I got icons updates

<img width="750" alt="Screen Shot 2021-01-16 at 11 52 43 PM" src="https://user-images.githubusercontent.com/14034784/104834748-59aeed00-5856-11eb-94e3-e688db60d8fb.png">


the [bookdown.pdf](https://bookdown.org/yihui/bookdown/bookdown.pdf) has the Icons next to the infobox, not inside the infobox. 
<img width="600" alt="Screen Shot 2021-01-16 at 11 35 02 PM" src="https://user-images.githubusercontent.com/14034784/104834339-86add080-5853-11eb-925b-0f3c828aba70.png">
