### ISSUE TITLE
NLP used inappropriately and got bad results

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#94]
## Automated grading

https://www.vice.com/en/article/pa7dj9/flawed-algorithms-are-grading-millions-of-students-essays
https://onlinelibrary.wiley.com/doi/full/10.1002/ets2.12192
https://youtu.be/bqCEUQq0z4o?t=180

> used in at least 22 US states

**Comment by juliasilge** [comment]
Closed in 0f078cf3ec88be03ce7b9084958bcd07303d494c
